---
- hosts: "{{ host_name }}"
  remote_user: ubuntu
  become: yes
  pre_tasks:
  - name: Update repositories cache and install "makepasswd" package
    apt:
      name: makepasswd
      state: present
      update_cache: yes

  - name: Update repositories cache and install whois package
    apt:
      name: whois
      state: present
      update_cache: yes

  - name: Generate password for new user
    shell: makepasswd --chars=20
    register: user_password

  - name: Generate encrypted password
    shell: mkpasswd --method=SHA-512 {{ user_password.stdout }}
    register: encrypted_user_password  
  tasks:
  - name: register user if its present on remote machine
    shell: /bin/cat /etc/passwd|grep {{ user_name }} | /usr/bin/wc -l | tr -d ''
    register: existing_user
  - name:  run the role if user is not present
    include_role: 
      name: usermanagement
    when: existing_user.stdout != '1'
