---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Ensure nginx is installed for elk proxy.
  apt:
    name: "nginx"
    state: present
  notify: restart nginx 
- name: Copy Nginx configuration file for elk proxy
  template:
    src: elk_proxy.j2
    dest: /etc/nginx/sites-available/elk_proxy.conf
- name: Create symbolic link
  file:
    src: /etc/nginx/sites-available/elk_proxy.conf
    dest: /etc/nginx/sites-enabled/elk_proxy.conf
    state: link
  notify: restart nginx

#- name: Restart service nginx
#  service:
#    name: nginx
#    enabled: yes
#    state: restarted

