---

#- name:  Install kibana from deb package by downloading from official site
#  apt:
#    deb: https://artifacts.elastic.co/downloads/kibana/kibana-7.10.1-amd64.deb 
- name: Copy kibana  configuration file
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
- name: Restart service kibana
  service:
    name: kibana
    enabled: yes
    state: restarted

