---
  - name: Create user account
    user: name={{ user_name }}
          password={{ encrypted_user_password.stdout }}
          state=present
          groups=sudo
          append=yes
          shell="/bin/bash"
          update_password=always

    register: user_created
  - name: permissions
    file: path=/home/devops
          state=directory
          owner=devops
          group=devops
          recurse=yes

  - name: Force user to change password
    shell: chage -d 0 {{ user_name }}
    when: user_created.changed

  - name: User created
    debug: msg="Password for {{ ansible_ssh_host }} is {{ user_password.stdout }}"
    when: user_created.changed
    register: ansible_ssh_host_values

  - name: backup password
    local_action: shell echo "{{ user_name }}  {{ ansible_ssh_host_values }} {{ user_password.stdout }}" >> /tmp/{{ user_name }}
